require 'snmpAccess'
module NTCIPOIDList
  class TheList
    def initialize
      @oidList = []
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsSignAccess", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dmsSignType", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsSignHeight", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsSignWidth", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsHorizontalBorder", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsVerticalBorder", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dmsLegend", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dmsBeaconType", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsSignTechnology", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "vmsCharacterHeightPixels", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "vmsCharacterWidthPixels", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "vmsSignHeightPixels", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "vmsSignWidthPixels", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "vmsHorizontalPitch", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "vmsVerticalPitch", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessString.new(oidName: "monochromeColor", size: 6, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "numFonts", size: 2, access: :ro)

      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "fontNumber", size: 2, access: :rw, tableName: "fontTable", tableColumn: 2, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessDisplayString.new(oidName: "fontName", size: 0, access: :rw, tableName: "fontTable", tableColumn: 3,nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "fontHeight", size: 2, access: :rw, tableName: "fontTable", tableColumn: 4,nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "fontCharSpacing", size: 2, access: :rw, tableName: "fontTable", tableColumn: 5,nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "fontLineSpacing", size: 2, access: :rw, tableName: "fontTable", tableColumn: 6,nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "fontVersionID", size: 2, access: :ro, tableName:  "fontTable", tableColumn: 7,nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "fontStatus", size: 1, access: :rw, tableName: "fontTable", tableColumn: 8,nTableIndexes: 1)

      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "maxFontCharacters", size: 2, access: :ro)


      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "characterWidth", size: 2, access: :rw, tableName: "characterTable", tableColumn: 2, nTableIndexes: 2)
      @oidList << SNMPAccess::OIDAccessString.new(oidName: "characterBitmap", size: 255, access: :rw, tableName: "characterTable", tableColumn: 3, nTableIndexes: 2)

      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "fontMaxCharacterSize", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "defaultBackgroundColor", size: 2, access: :rw)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "defaultForegroundColor", size: 2, access: :rw)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "defaultFlashOn", size: 2, access: :rw)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "defaultFlashOnActivate", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "defaultFlashOff", size: 2, access: :rw)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "defaultFlashOffActivate", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "defaultFont", size: 2, access: :rw)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "defaultFontActivate", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "defaultJustificationLine", size: 1, access: :rw)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "defaultJustificationLineActivate", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "defaultJustificationPage", size: 1, access: :rw)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "defaultJustificationPageActivate", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "defaultPageOnTime", size: 2, access: :rw)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "defaultPageOnTimeActivate", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "defaultPageOffTime", size: 2, access: :rw)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "defaultPageOffTimeActivate", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessString.new(oidName: "defaultBackgroundRGB", size: 3, access: :rw)
      @oidList << SNMPAccess::OIDAccessString.new(oidName: "defaultBackgroundRGBActivate", size: 3, access: :ro)
      @oidList << SNMPAccess::OIDAccessString.new(oidName: "defaultForegroundRGB", size: 3, access: :rw)
      @oidList << SNMPAccess::OIDAccessString.new(oidName: "defaultForegroundRGBActivate", size: 3, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "defaultCharacterSet", size: 1, access: :rw)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dmsColorScheme", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessString.new(oidName: "dmsSupportedMultiTags", size: 4, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsMaxNumberPages", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsMaxMultiStringLength", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsNumPermanentMsg", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsNumChangeableMsg", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsMaxChangeableMsg", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsFreeChangeableMemory", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsNumVolatileMsg", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsMaxVolatileMsg", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsFreeVolatileMemory", size: 2, access: :ro)

      @oidList << SNMPAccess::OIDAccessString.new(oidName: "dmsMessageMultiString", size: 255, access: :rw, tableName: "dmsMessageTable", tableColumn: 3, nTableIndexes: 2)
      @oidList << SNMPAccess::OIDAccessOwnerString.new(oidName: "dmsMessageOwner", size: 0, access: :rw, tableName: "dmsMessageTable", tableColumn: 4, nTableIndexes: 2)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "dmsMessageCRC", size: 4, access: :ro, tableName:  "dmsMessageTable", tableColumn: 5, nTableIndexes: 2)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsMessageBeacon", size: 2, access: :rw, tableName: "dmsMessageTable", tableColumn: 6, nTableIndexes: 2)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsMessagePixelService", size: 2, access: :rw, tableName: "dmsMessageTable", tableColumn: 7, nTableIndexes: 2)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsMessageRunTimePriority", size: 2, access: :rw, tableName: "dmsMessageTable", tableColumn: 8, nTableIndexes: 2)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dmsMessageStatus", size: 1, access: :rw, tableName: "dmsMessageTable", tableColumn: 9, nTableIndexes: 2)

      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dmsValidateMessageError", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dmsControlMode", size: 1, access: :rw)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsSWReset", size: 2, access: :rw)
      @oidList << SNMPAccess::OIDAccessMessageActivationCode.new(oidName: "dmsActivateMessage", size: 12, access: :rw)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsMessageTimeRemaining", size: 2, access: :rw)
      @oidList << SNMPAccess::OIDAccessMessageIDCode.new(oidName: "dmsMsgTableSource", size: 0, access: :ro)
      @oidList << SNMPAccess::OIDAccessIPAddress.new(oidName: "dmsMsgRequesterID", size: 0, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dmsMsgSourceMode", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessMessageIDCode.new(oidName: "dmsShortPowerRecoveryMessage", size: 0, access: :rw)
      @oidList << SNMPAccess::OIDAccessMessageIDCode.new(oidName: "dmsLongPowerRecoveryMessage", size: 0, access: :rw)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsShortPowerLossTime", size: 2, access: :rw)
      @oidList << SNMPAccess::OIDAccessMessageIDCode.new(oidName: "dmsResetMessage", size: 0, access: :rw)
      @oidList << SNMPAccess::OIDAccessMessageIDCode.new(oidName: "dmsCommunicationsLossMessage", size: 0, access: :rw)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsTimeCommLoss", size: 2, access: :rw)
      @oidList << SNMPAccess::OIDAccessMessageIDCode.new(oidName: "dmsPowerLossMessage", size: 0, access: :rw)
      @oidList << SNMPAccess::OIDAccessMessageIDCode.new(oidName: "dmsEndDurationMessage", size: 0, access: :rw)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dmsMemoryMgmt", size: 1, access: :rw)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dmsActivateMsgError", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dmsMultiSyntaxError", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsMultiSyntaxErrorPosition", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessDisplayString.new(oidName: "dmsMultiOtherErrorDescription", size: 0, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "vmsPixelServiceDuration", size: 2, access: :rw)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "vmsPixelServiceFrequency", size: 2, access: :rw)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "vmsPixelServiceTime", size: 2, access: :rw)
      @oidList << SNMPAccess::OIDAccessMessageActivationCode.new(oidName: "dmsActivateErrorMsgCode", size: 0, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dmsActivateMessageState", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dmsIllumControl", size: 1, access: :rw)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsIllumMaxPhotocellLevel", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsIllumPhotocellLevelStatus", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsIllumNumBrightLevels", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsIllumBrightLevelStatus", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsIllumManLevel", size: 2, access: :rw)
      @oidList << SNMPAccess::OIDAccessString.new(oidName: "dmsIllumBrightnessValues", size: 255, access: :rw)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dmsIllumBrightnessValuesError", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsIllumLightOutputStatus", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "numActionTableEntries", size: 2, access: :ro)

      @oidList << SNMPAccess::OIDAccessMessageIDCode.new(oidName: "dmsActionMsgCode", size: 0, access: :rw, tableName: "dmsActionTable", tableColumn: 2, nTableIndexes: 1)

      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "statMultiFieldRows", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "statMultiFieldCode", size: 2, access: :ro, tableName:  "statMultiFieldTable", tableColumn: 2, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessString.new(oidName: "statMultiCurrentFieldValue", size: 50, access: :ro, tableName:  "statMultiFieldTable", tableColumn: 3, nTableIndexes: 1)

      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsCurrentSpeed", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsCurrentSpeedLimit", size: 2, access: :rw)
      @oidList << SNMPAccess::OIDAccessCounter.new(oidName: "watchdogFailureCount", size: 0, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsStatDoorOpen", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "shortErrorStatus", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "controllerErrorStatus", size: 2, access: :ro)

      @oidList << SNMPAccess::OIDAccessDisplayString.new(oidName: "dmsPowerDescription", size: 0, access: :ro, tableName:  "dmsPowerStatusTable", tableColumn: 2, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessDisplayString.new(oidName: "dmsPowerMfrStatus", size: 0, access: :ro, tableName:  "dmsPowerStatusTable", tableColumn: 3, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dmsPowerStatus", size: 1, access: :ro, tableName:  "dmsPowerStatusTable", tableColumn: 4, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsPowerVoltage", size: 2, access: :ro, tableName:  "dmsPowerStatusTable", tableColumn: 5, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dmsPowerType", size: 1, access: :ro, tableName:  "dmsPowerStatusTable", tableColumn: 6, nTableIndexes: 1)


      @oidList << SNMPAccess::OIDAccessString.new(oidName: "dmsPowerFailureStatusMap", size: 64, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsPowerNumRows", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsPowerIndex", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessDisplayString.new(oidName: "dmsPowerDescription", size: 0, access: :ro)
      @oidList << SNMPAccess::OIDAccessDisplayString.new(oidName: "dmsPowerMfrStatus", size: 0, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dmsPowerStatus", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsPowerVoltage", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dmsPowerType", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessString.new(oidName: "fanFailures", size: 4, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "fanTestActivation", size: 1, access: :rw)
      @oidList << SNMPAccess::OIDAccessString.new(oidName: "dmsClimateCtrlStatusMap", size: 64, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsClimateCtrlNumRows", size: 2, access: :ro)

      @oidList << SNMPAccess::OIDAccessDisplayString.new(oidName: "dmsClimateCtrlDescription", size: 0, access: :ro, tableName:  "dmsClimateCtrlStatusTable", tableColumn: 2, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessDisplayString.new(oidName: "dmsClimateCtrlMfrStatus", size: 0, access: :ro, tableName:  "dmsClimateCtrlStatusTable", tableColumn: 3, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dmsClimateCtrlErrorStatus", size: 1, access: :ro, tableName:  "dmsClimateCtrlStatusTable", tableColumn: 4, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsClimateCtrlOnStatus", size: 2, access: :ro, tableName:  "dmsClimateCtrlStatusTable", tableColumn: 5, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dmsClimateCtrlTestActivation", size: 1, access: :rw, tableName: "dmsClimateCtrlStatusTable", tableColumn: 6, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessDisplayString.new(oidName: "dmsClimateCtrlAbortReason", size: 0, access: :ro, tableName:  "dmsClimateCtrlStatusTable", tableColumn: 7, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dmsClimateCtrlType", size: 1, access: :ro, tableName:  "dmsClimateCtrlStatusTable", tableColumn: 8, nTableIndexes: 1)

      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "pixelFailureTableNumRows", size: 2, access: :ro)

      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "pixelFailureXLocation", size: 2, access: :ro, tableName: "pixelFailureTable", tableColumn: 3, nTableIndexes: 2)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "pixelFailureYLocation", size: 2, access: :ro, tableName: "pixelFailureTable", tableColumn: 4, nTableIndexes: 2)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "pixelFailureStatus", size: 2, access: :ro, tableName: "pixelFailureTable", tableColumn: 5, nTableIndexes: 2)

      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "pixelTestActivation", size: 1, access: :rw)

      @oidList << SNMPAccess::OIDAccessString.new(oidName: "dmsPixelStatus", size: 400, access: :ro, tableName:  "pixelStatusTable", tableColumn: 2, nTableIndexes: 1)

      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsPixelFailureTestRows", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsPixelFailureMessageRows", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessString.new(oidName: "lampFailureStuckOn", size: 255, access: :ro)
      @oidList << SNMPAccess::OIDAccessString.new(oidName: "lampFailureStuckOff", size: 255, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "lampTestActivation", size: 1, access: :rw)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsLampNumRows", size: 2, access: :ro)

      @oidList << SNMPAccess::OIDAccessDisplayString.new(oidName: "dmsLampDescription", size: 0, access: :ro, tableName:  "dmsLampStatusTable", tableColumn: 2, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessDisplayString.new(oidName: "dmsLampMfrStatus", size: 0, access: :ro, tableName:  "dmsLampStatusTable", tableColumn: 3, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dmsLampStatus", size: 1, access: :ro, tableName:  "dmsLampStatusTable", tableColumn: 4, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsLampPixelTop", size: 2, access: :ro, tableName:  "dmsLampStatusTable", tableColumn: 5, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsLampPixelLeft", size: 2, access: :ro, tableName:  "dmsLampStatusTable", tableColumn: 6, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsLampPixelBottom", size: 2, access: :ro, tableName:  "dmsLampStatusTable", tableColumn: 7, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsLampPixelRight", size: 2, access: :ro, tableName:  "dmsLampStatusTable", tableColumn: 8, nTableIndexes: 1)


      @oidList << SNMPAccess::OIDAccessString.new(oidName: "dmsDrumStatusMap", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsDrumNumRows", size: 2, access: :ro)

      @oidList << SNMPAccess::OIDAccessDisplayString.new(oidName: "dmsDrumDescription", size: 0, access: :ro, tableName:  "dmsDrumStatusTable", tableColumn: 2, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessDisplayString.new(oidName: "dmsDrumMfrStatus", size: 0, access: :ro, tableName:  "dmsDrumStatusTable", tableColumn: 3, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dmsDrumStatus", size: 1, access: :ro, tableName:  "dmsDrumStatusTable", tableColumn: 4, nTableIndexes: 1)

      @oidList << SNMPAccess::OIDAccessString.new(oidName: "dmsLightSensorStatusMap", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsLightSensorNumRows", size: 2, access: :ro)

      @oidList << SNMPAccess::OIDAccessDisplayString.new(oidName: "dmsLightSensorDescription", size: 0, access: :ro, tableName:  "dmsLightSensorStatusTable", tableColumn: 2, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsLightSensorCurrentReading", size: 2, access: :ro, tableName:  "dmsLightSensorStatusTable", tableColumn: 3, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dmsLightSensorStatus", size: 1, access: :ro, tableName:  "dmsLightSensorStatusTable", tableColumn: 4, nTableIndexes: 1)

      @oidList << SNMPAccess::OIDAccessString.new(oidName: "dmsHumiditySensorStatusMap", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsHumiditySensorNumRows", size: 2, access: :ro)

      @oidList << SNMPAccess::OIDAccessDisplayString.new(oidName: "dmsHumiditySensorDescription", size: 0, access: :ro, tableName:  "dmsHumiditySensorStatusTable", tableColumn: 2, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsHumiditySensorCurrentReading", size: 2, access: :ro, tableName:  "dmsHumiditySensorStatusTable", tableColumn: 3, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dmsHumiditySensorStatus", size: 1, access: :ro, tableName:  "dmsHumiditySensorStatusTable", tableColumn: 4, nTableIndexes: 1)


      @oidList << SNMPAccess::OIDAccessString.new(oidName: "dmsTempSensorStatusMap", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsTempSensorNumRows", size: 2, access: :ro)

      @oidList << SNMPAccess::OIDAccessDisplayString.new(oidName: "dmsTempSensorDescription", size: 0, access: :ro, tableName:  "dmsTempSensorStatusTable", tableColumn: 2, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "dmsTempSensorCurrentReading", size: 2, access: :ro, tableName:  "dmsTempSensorStatusTable", tableColumn: 3, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "dmsTempSensorHighWarningTemperature", size: 2, access: :ro, tableName:  "dmsTempSensorStatusTable", tableColumn: 4, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "dmsTempSensorLowWarningTemperature", size: 2, access: :ro, tableName:  "dmsTempSensorStatusTable", tableColumn: 5, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "dmsTempSensorHighCriticalTemperature", size: 2, access: :ro, tableName:  "dmsTempSensorStatusTable", tableColumn: 6, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "dmsTempSensorLowCriticalTemperature", size: 2, access: :ro, tableName:  "dmsTempSensorStatusTable", tableColumn: 7, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dmsTempSensorStatus", size: 1, access: :ro, tableName:  "dmsTempSensorStatusTable", tableColumn: 8, nTableIndexes: 1)

      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "dmsTempSensorHighestCriticalTempThreshold", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "dmsTempSensorLowestCriticalTempThreshold", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "signVolts", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "lowFuelThreshold", size: 2, access: :rw)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "fuelLevel", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "engineRPM", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "lineVolts", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "powerSource", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "tempMinCtrlCabinet", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "tempMaxCtrlCabinet", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "tempMinAmbient", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "tempMaxAmbient", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "tempMinSignHousing", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "tempMaxSignHousing", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessString.new(oidName: "tempSensorWarningMap", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessString.new(oidName: "tempSensorCriticalTempMap", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsGraphicMaxEntries", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsGraphicNumEntries", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsGraphicMaxSize", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessCounter.new(oidName: "availableGraphicMemory", size: 0, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsGraphicBlockSize", size: 2, access: :ro)

      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsGraphicNumber", size: 2, access: :rw, tableName: "dmsGraphicTable", tableColumn: 2, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessDisplayString.new(oidName: "dmsGraphicName", size: 0, access: :rw, tableName: "dmsGraphicTable", tableColumn: 3, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsGraphicHeight", size: 2, access: :rw, tableName: "dmsGraphicTable", tableColumn: 4, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsGraphicWidth", size: 2, access: :rw, tableName: "dmsGraphicTable", tableColumn: 5, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dmsGraphicType", size: 1, access: :rw, tableName: "dmsGraphicTable", tableColumn: 6, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsGraphicID", size: 2, access: :ro, tableName:  "dmsGraphicTable", tableColumn: 7, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsGraphicTransparentEnabled", size: 2, access: :rw, tableName: "dmsGraphicTable", tableColumn: 8, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessString.new(oidName: "dmsGraphicTransparentColor", size: 3, access: :rw, tableName: "dmsGraphicTable", tableColumn: 9, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dmsGraphicStatus", size: 1, access: :rw, tableName: "dmsGraphicTable", tableColumn: 10, nTableIndexes: 1)


      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dmsGraphicBlockNumber", size: 2, access: :ro, tableName:  "dmsGraphicBitmapTable", tableColumn: 2, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessString.new(oidName: "dmsGraphicBlockBitmap", size: 255, access: :rw, tableName: "dmsGraphicBitmapTable", tableColumn: 3, nTableIndexes: 2)
#####
## 1201v03
#####
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "globalSetIDParameter", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "globalMaxModules", size: 2, access: :ro)

      @oidList << SNMPAccess::OIDAccessString.new(oidName: "moduleMake", size: 255, access: :ro, tableName:  "globalModuleTable", tableColumn: 2, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessObjectID.new(oidName: "moduleDeviceNode", size: 0, access: :ro, tableName:  "globalModuleTable", tableColumn: 3, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessString.new(oidName: "moduleModel", size: 255, access: :ro, tableName:  "globalModuleTable", tableColumn: 4, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessString.new(oidName: "moduleVersion", size: 255, access: :ro, tableName:  "globalModuleTable", tableColumn: 5, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "moduleType", size: 1, access: :ro, tableName:  "globalModuleTable", tableColumn: 6, nTableIndexes: 1)

      @oidList << SNMPAccess::OIDAccessString.new(oidName: "controllerBaseStandards", size: 256, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dbCreateTransaction", size: 1, access: :rw)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dbErrorType", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessObjectID.new(oidName: "dbErrorID", size: 0, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dbTransactionID", size: 2, access: :rw)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dbMakeID", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dbVerifyStatus", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessString.new(oidName: "dbVerifyError", size: 255, access: :ro)
      @oidList << SNMPAccess::OIDAccessCounter.new(oidName: "globalTime", size: 0, access: :rw)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "globalDaylightSaving", size: 1, access: :rw)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "maxTimeBaseScheduleEntries", size: 2, access: :ro)

      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "timeBaseScheduleMonth", size: 2, access: :rw, tableName: "timeBaseScheduleTable", tableColumn: 2, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "timeBaseScheduleDay", size: 2, access: :rw, tableName: "timeBaseScheduleTable", tableColumn: 3, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "timeBaseScheduleDate", size: 2, access: :rw, tableName: "timeBaseScheduleTable", tableColumn: 4, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "timeBaseScheduleDayPlan", size: 2, access: :rw, tableName: "timeBaseScheduleTable", tableColumn: 5, nTableIndexes: 1)


      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "maxDayPlans", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "maxDayPlanEvents", size: 2, access: :ro)

      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dayPlanHour", size: 2, access: :rw, tableName: "timeBaseDayPlanTable", tableColumn: 3, nTableIndexes: 2)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dayPlanMinute", size: 2, access: :rw, tableName: "timeBaseDayPlanTable", tableColumn: 4, nTableIndexes: 2)
      @oidList << SNMPAccess::OIDAccessObjectID.new(oidName: "dayPlanActionNumberOID", size: 0, access: :rw, tableName: "timeBaseDayPlanTable", tableColumn: 5, nTableIndexes: 2)

      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dayPlanStatus", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "timeBaseScheduleTableStatus", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "globalLocalTimeDifferential", size: 2, access: :rw)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "controllerStandardTimeZone", size: 2, access: :rw)
      @oidList << SNMPAccess::OIDAccessCounter.new(oidName: "controllerLocalTime", size: 0, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "maxDaylightSavingEntries", size: 2, access: :ro)

      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dstBeginMonth", size: 1, access: :rw, tableName: "dstTable", tableColumn: 2, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dstBeginOccurrences", size: 1, access: :rw, tableName: "dstTable", tableColumn: 3, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dstBeginDayOfWeek", size: 1, access: :rw, tableName: "dstTable", tableColumn: 4, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dstBeginDayOfMonth", size: 2, access: :rw, tableName: "dstTable", tableColumn: 5, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dstBeginSecondsToTransition", size: 2, access: :rw, tableName: "dstTable", tableColumn: 6, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dstEndMonth", size: 1, access: :rw, tableName:" dstTable", tableColumn: 7, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dstEndOccurrences", size: 1, access: :rw, tableName: "dstTable", tableColumn: 8, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "dstEndDayOfWeek", size: 1, access: :rw, tableName: "dstTable", tableColumn: 9, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dstEndDayOfMonth", size: 2, access: :rw, tableName: "dstTable", tableColumn: 10, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dstEndSecondsToTransition", size: 2, access: :rw, tableName: "dstTable", tableColumn: 11, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "dstSecondsToAdjust", size: 2, access: :rw, tableName: "dstTable", tableColumn: 12, nTableIndexes: 1)

      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "maxGroupAddresses", size: 2, access: :ro)

      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "hdlcGroupAddress", size: 4, access: :rw, tableName: "hdlcGroupAddressTable", tableColumn: 2, nTableIndexes: 1)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "hdlcGroupAddressNumber", size: 2, access: :rw, tableName: "hdlcGroupAddressTable", tableColumn: 3, nTableIndexes: 1)

      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "maxAuxIOv2TableNumDigitalPorts", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "maxAuxIOv2TableNumAnalogPorts", size: 2, access: :ro)

      @oidList << SNMPAccess::OIDAccessDisplayString.new(oidName: "auxIOv2PortDescription", size: 0, access: :rw, tableName: "auxIOv2Table", tableColumn: 3, nTableIndexes: 2)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "auxIOv2PortResolution", size: 2, access: :ro, tableName:  "auxIOv2Table", tableColumn: 4, nTableIndexes: 2)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "auxIOv2PortValue", size: 2, access: :rw, tableName: "auxIOv2Table", tableColumn: 5, nTableIndexes: 2)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "auxIOv2PortDirection", size: 1, access: :ro, tableName:  "auxIOv2Table", tableColumn: 6, nTableIndexes: 2)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "auxIOv2PortLastCommandedState", size: 2, access: :ro, tableName:  "auxIOv2Table", tableColumn: 7, nTableIndexes: 2)

      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "maxAuxIODigital", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "maxAuxIOAnalog", size: 2, access: :ro)

      @oidList << SNMPAccess::OIDAccessDisplayString.new(oidName: "auxIODescription", size: 0, access: :rw, tableName: "auxIOTable", tableColumn: 3, nTableIndexes: 2)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "auxIOResolution", size: 2, access: :ro, tableName:  "auxIOTable", tableColumn: 4, nTableIndexes: 2)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "auxIOValue", size: 2, access: :rw, tableName: "auxIOTable", tableColumn: 5, nTableIndexes: 2)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "auxIOPortDirection", size: 1, access: :ro, tableName:  "auxIOTable", tableColumn: 6, nTableIndexes: 2)
#####
## 1204-2005
#####
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "essNtcipCategory", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessDisplayString.new(oidName: "essNtcipSiteDescription", size: 0, access: :rw)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essTypeofStation", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essDoorStatus", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essBatteryStatus", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essLineVolts", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessOerString.new(oidName: "essStationMetaDataBlock", size: 0, access: :ro)
      @oidList << SNMPAccess::OIDAccessOerString.new(oidName: "essWeatherBlock", size: 0, access: :ro)
      @oidList << SNMPAccess::OIDAccessOerString.new(oidName: "essMobileBlock", size: 0, access: :ro)
      @oidList << SNMPAccess::OIDAccessInt32.new(oidName: "essLatitude", size: 4, access: :ro)
      @oidList << SNMPAccess::OIDAccessInt32.new(oidName: "essLongitude", size: 4, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essVehicleSpeed", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essVehicleBearing", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessCounter.new(oidName: "essOdometer", size: 0, access: :ro)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "essReferenceHeight", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "essPressureHeight", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "essWindSensorHeight", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essAtmosphericPressure", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essAvgWindDirection", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essAvgWindSpeed", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essSpotWindDirection", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essSpotWindSpeed", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "essWindSituation", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essMaxWindGustSpeed", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essMaxWindGustDir", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "windSensorTableNumSensors", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "windSensorIndex", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "windSensorHeight", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessDisplayString.new(oidName: "windSensorLocation", size: 0, access: :rw)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "windSensorAvgSpeed", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "windSensorAvgDirection", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "windSensorSpotSpeed", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "windSensorSpotDirection", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "windSensorGustSpeed", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "windSensorGustDirection", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "windSensorSituation", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essNumTemperatureSensors", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essTemperatureSensorIndex", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "essTemperatureSensorHeight", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "essAirTemperature", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "essWetbulbTemp", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "essDewpointTemp", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "essMaxTemp", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "essMinTemp", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essRelativeHumidity", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essWaterDepth", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essAdjacentSnowDepth", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essRoadwaySnowDepth", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essRoadwaySnowPackDepth", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "essPrecipYesNo", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essPrecipRate", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essSnowfallAccumRate", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "essPrecipSituation", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essIceThickness", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essPrecipitationStartTime", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essPrecipitationEndTime", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essPrecipitationOneHour", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essPrecipitationThreeHours", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essPrecipitationSixHours", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essPrecipitationTwelveHours", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essPrecipitation24Hours", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "precipitationSensorModelInformation", size: 2, access: :rw)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "waterLevelSensorTableNumSensors", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "waterLevelSensorIndex", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "waterLevelSensorReading", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essSolarRadiation", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essTotalSun", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "essCloudSituation", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "essInstantaneousTerrestrialRadiation", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "essInstantaneousSolarRadiation", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "essTotalRadiation", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt32.new(oidName: "essTotalRadiationPeriod", size: 4, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt32.new(oidName: "essVisibility", size: 4, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "essVisibilitySituation", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "numEssPavementSensors", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essPavementSensorIndex", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessDisplayString.new(oidName: "essPavementSensorLocation", size: 0, access: :rw)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "essPavementType", size: 1, access: :rw)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "essPavementElevation", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essPavementExposure", size: 2, access: :rw)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "essPavementSensorType", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "essSurfaceStatus", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "essSurfaceTemperature", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "essPavementTemperature", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essSurfaceWaterDepth", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essSurfaceSalinity", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essSurfaceConductivity", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "essSurfaceFreezePoint", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "essSurfaceBlackIceSignal", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "essPavementSensorError", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essSurfaceIceOrWaterDepth", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essSurfaceConductivityV2", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "pavementSensorModelInformation", size: 2, access: :rw)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "pavementSensorTemperatureDepth", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "numEssSubSurfaceSensors", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essSubSurfaceSensorIndex", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessDisplayString.new(oidName: "essSubSurfaceSensorLocation", size: 0, access: :rw)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "essSubSurfaceType", size: 1, access: :rw)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essSubSurfaceSensorDepth", size: 2, access: :rw)
      @oidList << SNMPAccess::OIDAccessInt.new(oidName: "essSubSurfaceTemperature", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essSubSurfaceMoisture", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "essSubSurfaceSensorError", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessOerString.new(oidName: "essPavementBlock", size: 0, access: :ro)
      @oidList << SNMPAccess::OIDAccessOerString.new(oidName: "essSubsurfaceData", size: 0, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essMobileFriction", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "essMobileObservationGroundState", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "essMobileObservationPavement", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "numEssTreatments", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essPavementTreatmentIndex", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "essPaveTreatProductType", size: 1, access: :rw)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "essPaveTreatProductForm", size: 1, access: :rw)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essPercentProductMix", size: 2, access: :rw)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essPaveTreatmentAmount", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essPaveTreatmentWidth", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessOerString.new(oidName: "pavementTreatmentBlock", size: 0, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "ptsOperationalMode", size: 1, access: :rw)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "ptsCommandState", size: 1, access: :rw)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "ptsSprayerState", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt32.new(oidName: "ptsSignalDuration", size: 4, access: :rw)
      @oidList << SNMPAccess::OIDAccessCounter.new(oidName: "ptsSignalEventCount", size: 0, access: :ro)
      @oidList << SNMPAccess::OIDAccessCounter.new(oidName: "ptsLastSignalEvent", size: 0, access: :ro)
      @oidList << SNMPAccess::OIDAccessCounter.new(oidName: "ptsActiveEventCount", size: 0, access: :ro)
      @oidList << SNMPAccess::OIDAccessCounter.new(oidName: "ptsInactiveEventCount", size: 0, access: :ro)
      @oidList << SNMPAccess::OIDAccessCounter.new(oidName: "ptsLastActiveEvent", size: 0, access: :ro)
      @oidList << SNMPAccess::OIDAccessCounter.new(oidName: "ptsLastInactiveEvent", size: 0, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "ptsError", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessString.new(oidName: "ptsMonitoringDetectors", size: 4, access: :rw)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essCO", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essCO2", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essNO", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essNO2", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essSO2", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essO3", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essPM10", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessOerString.new(oidName: "essAirQualityData", size: 0, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essSnapshotNumberOfCameras", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessUInt.new(oidName: "essSnapshotCameraIndex", size: 2, access: :ro)
      @oidList << SNMPAccess::OIDAccessDisplayString.new(oidName: "essSnapshotCameraDescription", size: 0, access: :rw)
      @oidList << SNMPAccess::OIDAccessDisplayString.new(oidName: "essSnapshotCameraStoragePath", size: 0, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "essSnapshotCameraCommand", size: 1, access: :ro)
      @oidList << SNMPAccess::OIDAccessEnum.new(oidName: "essSnapshotCameraError", size: 1, access: :ro)
    end
    def get_list
      @oidList
    end
    def locate_oid name
      theOIDList = @oidList.select { |oid| oid.name == name }
      theOIDList[0]
    end
  end
end
